/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.tapjoy;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
//import org.appcelerator.titanium.TiAp
import org.appcelerator.kroll.common.Log;

import com.tapjoy.TapjoyConnect;

@Kroll.module(name="TapjoyAndroid", id="ti.tapjoy")
public class TapjoyAndroidModule extends KrollModule
{
	private TiApplication appContext = TiApplication.getInstance();

	// Standard Debugging variables
	private static final String TAG = "TapjoyAndroidModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TapjoyAndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}
	
	@Kroll.method
	public String requestTapjoyConnect(String appID, String secretKey) {
		try{
			Log.d(TAG, "calling requestTapjoyConnect:"+appID+":"+secretKey);
			TapjoyConnect.requestTapjoyConnect(appContext, appID, secretKey);
			return "ok";
		}catch(Exception e){
			return e.toString();
		}
	}

}

